create table ajustes_inventario (id bigint not null auto_increment, cantidad decimal(10,2) not null, fecha datetime(6) not null, motivo varchar(100) not null, observaciones varchar(255), almacenes_id integer not null, productos_id integer not null, usuarios_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table almacenes (id integer not null auto_increment, categoria_almacen enum ('MATERIA_PRIMA','PRODUCTO_TERMINADO','MATERIAL_EMPAQUE','SUMINISTROS','OBSOLETOS') not null, nombre varchar(100) not null, tipo_almacen enum ('PRINCIPAL','SATELITE') not null, ubicacion varchar(100) not null, primary key (id)) ENGINE=InnoDB;
create table archivos_evaluacion (evaluacion_id bigint not null, archivo varchar(255) not null, nombre_visible varchar(100)) ENGINE=InnoDB;
create table bitacora_cambios_inventario (id bigint not null auto_increment, campo_modificado varchar(45) not null, fecha_cambio datetime(6) not null, registro_id bigint not null, tabla_afectada varchar(45) not null, valor_ant varchar(255) not null, valor_nuevo varchar(255) not null, usuarios_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table capa (id bigint not null auto_increment, estado ENUM('ACTIVA','CERRADA','VENCIDA') not null, fecha_cierre datetime(6), fecha_inicio datetime(6) not null, observaciones TEXT, tipo ENUM('CORRECTIVA','PREVENTIVA') not null, no_conformidad_id bigint not null, responsable_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table categorias_producto (id bigint not null auto_increment, nombre varchar(100) not null, tipo enum ('MATERIA_PRIMA','PRODUCTO_TERMINADO','MATERIAL_EMPAQUE','SUMINISTROS','OBSOLETOS') not null, primary key (id)) ENGINE=InnoDB;
create table checklist_calidad (id bigint not null auto_increment, descripcion_general TEXT, fecha_creacion datetime(6) not null, tipo_checklist ENUM('ALMACENAMIENTO','LIMPIEZA','EQUIPOS') not null, creado_por_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table cierres_produccion (id bigint not null auto_increment, cantidad decimal(10,2) not null, cerrada_incompleta bit, fecha_cierre datetime(6) not null, observacion varchar(255), tipo enum ('PARCIAL','TOTAL') not null, turno varchar(255), usuario_id bigint, usuario_nombre varchar(100), orden_produccion_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table control_calidad_proceso (id bigint not null auto_increment, cumple bit, observaciones TEXT, parametro varchar(255), valor_medido varchar(255), detalle_etapa_id bigint, evaluado_por_id bigint, primary key (id)) ENGINE=InnoDB;
create table detalle_etapa (id bigint not null auto_increment, fecha_fin datetime(6), fecha_inicio datetime(6), observaciones TEXT, etapa_id bigint, usuario_id bigint, orden_produccion_id bigint, primary key (id)) ENGINE=InnoDB;
create table detalle_formula (id bigint not null auto_increment, cantidad_necesaria decimal(38,8) not null, obligatorio bit, formula_id bigint, insumo_id integer, unidad_medida_id bigint, primary key (id)) ENGINE=InnoDB;
create table documento_formula (id bigint not null auto_increment, fecha_subida datetime(6), nombre_archivo varchar(255), ruta_archivo varchar(255), tipo_documento enum ('MSDS','INSTRUCTIVO','PROCEDIMIENTO'), formula_id bigint, usuario_id bigint, primary key (id)) ENGINE=InnoDB;
create table especificaciones_calidad (id bigint not null auto_increment, metodo_ensayo varchar(100) not null, parametro varchar(45) not null, unidad varchar(45) not null, valor_maximo decimal(10,2) not null, valor_minimo decimal(10,2) not null, productos_id integer not null, primary key (id)) ENGINE=InnoDB;
create table etapa_produccion (id bigint not null auto_increment, estado enum ('PENDIENTE','EN_PROCESO','FINALIZADA') not null, fecha_fin datetime(6), fecha_inicio datetime(6), nombre_etapa varchar(255) not null, secuencia integer not null, usuario_id bigint, usuario_nombre varchar(100), orden_produccion_id bigint, primary key (id)) ENGINE=InnoDB;
create table etapa_plantilla (id bigint not null auto_increment, activo bit not null, nombre varchar(150) not null, secuencia integer not null, producto_id integer not null, primary key (id)) ENGINE=InnoDB;
create table evaluaciones_calidad (id bigint not null auto_increment, fecha_evaluacion datetime(6) not null, observaciones TEXT not null, resultado ENUM('CONFORME','NO_CONFORME') not null, tipo_evaluacion ENUM('FISICO_QUIMICO','MICROBIOLOGICO') not null, lotes_productos_id bigint not null, usuarios_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table formula_producto (id bigint not null auto_increment, activo bit not null, estado enum ('BORRADOR','EN_REVISION','APROBADA','RECHAZADA'), fecha_actualizacion datetime(6), fecha_creacion datetime(6), observacion varchar(500), version varchar(255), actualizado_por_id bigint, creado_por_id bigint, producto_id integer, primary key (id)) ENGINE=InnoDB;
create table historial_estado_orden (id bigint not null auto_increment, estado enum ('CREADA','ENVIADA','PARCIALMENTE_RECIBIDA','RECIBIDA_COMPLETAMENTE','CERRADA','CANCELADA','RECHAZADA') not null, fecha_cambio datetime(6) not null, observaciones varchar(255), usuario_id bigint not null, orden_compra_id integer not null, primary key (id)) ENGINE=InnoDB;
create table item_checklist (id bigint not null auto_increment, cumple bit, descripcion_item TEXT not null, fecha_revision datetime(6) not null, observaciones TEXT, checklist_id bigint not null, revisado_por_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table lotes_productos (id bigint not null auto_increment, agotado bit not null, codigo_lote varchar(100) not null, estado enum ('DISPONIBLE','EN_CUARENTENA','RETENIDO','RECHAZADO','VENCIDO','LIBERADO') not null, fecha_agotado datetime(6), fecha_fabricacion datetime(6), fecha_liberacion datetime(6), fecha_vencimiento datetime(6), stock_lote decimal(10,2) not null, stock_reservado decimal(18,6) not null, temperatura_almacenamiento float(53), almacenes_id integer not null, orden_produccion_id bigint, produccion_id bigint, productos_id integer not null, usuarios_liberador_id bigint, primary key (id)) ENGINE=InnoDB;
create table motivos_movimiento (id bigint not null auto_increment, descripcion varchar(255) not null, motivo enum ('AJUSTE_NEGATIVO','AJUSTE_POSITIVO','DEVOLUCION_DESDE_PRODUCCION','DEVOLUCION_DE_PROVEEDOR','DEVOLUCION_A_PROVEEDOR','ENTRADA_PRODUCTO_TERMINADO','ENTRADA_REPROCESO','RECEPCION_COMPRA','RECEPCION_DEVOLUCION_CLIENTE','SALIDA_MUESTRA_CALIDAD','SALIDA_PRODUCCION','SALIDA_CLIENTE','TRANSFERENCIA_INTERNA_PRODUCCION','TRANSFERENCIA_GENERAL','LIBERACION_CALIDAD','RECHAZO_CALIDAD') not null, primary key (id)) ENGINE=InnoDB;
create table movimientos_inventario (id bigint not null auto_increment, cantidad decimal(10,2) not null, clasificacion enum ('AJUSTE_NEGATIVO','AJUSTE_POSITIVO','DEVOLUCION_DESDE_PRODUCCION','DEVOLUCION_DE_PROVEEDOR','DEVOLUCION_A_PROVEEDOR','ENTRADA_PRODUCTO_TERMINADO','ENTRADA_REPROCESO','RECEPCION_COMPRA','RECEPCION_DEVOLUCION_CLIENTE','SALIDA_MUESTRA_CALIDAD','SALIDA_PRODUCCION','SALIDA_CLIENTE','TRANSFERENCIA_INTERNA_PRODUCCION','TRANSFERENCIA_GENERAL','LIBERACION_CALIDAD','RECHAZO_CALIDAD'), codigo_recepcion varchar(32), doc_referencia varchar(45), fecha_ingreso datetime(6) not null, tipo_mov enum ('AJUSTE','DEVOLUCION','ENTRADA','RECEPCION','SALIDA','TRANSFERENCIA') not null, almacen_destino_id integer, almacen_origen_id integer, lotes_productos_id bigint not null, motivos_movimiento_id bigint not null, ordenes_compra_id integer, orden_compra_detalle_id bigint, orden_produccion_id bigint, productos_id integer not null, proveedores_id integer, recepcion_oc_id bigint, registrado_por_id bigint not null, solicitud_movimiento_id bigint, tipos_movimiento_detalle_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table no_conformidad (id bigint not null auto_increment, codigo varchar(100) not null, descripcion TEXT, evidencia varchar(255), fecha_registro datetime(6) not null, origen ENUM('PRODUCTO','LOTE','PROVEEDOR','PROCESO') not null, severidad ENUM('CRITICA','MAYOR','MENOR') not null, usuario_reporta_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table orden_compra_detalle (id bigint not null auto_increment, cantidad decimal(10,3) not null, cantidad_recibida decimal(10,3) not null, iva decimal(5,2) not null, valor_total decimal(12,3) not null, valor_unitario decimal(10,3) not null, ordenes_compra_id integer not null, productos_id integer not null, primary key (id)) ENGINE=InnoDB;
create table ordenes_compra (id integer not null auto_increment, codigo_orden varchar(255) not null, estado enum ('CREADA','ENVIADA','PARCIALMENTE_RECIBIDA','RECIBIDA_COMPLETAMENTE','CERRADA','CANCELADA','RECHAZADA') not null, fecha_orden datetime(6) not null, observaciones varchar(255), proveedor_id integer not null, primary key (id)) ENGINE=InnoDB;
create table orden_produccion (id bigint not null auto_increment, cantidad_producida DECIMAL(10,2) DEFAULT 0 not null, cantidad_producida_acumulada DECIMAL(10,2) DEFAULT 0 not null, cantidad_programada decimal(10,2) not null, codigo_orden varchar(255) not null, estado enum ('CREADA','EN_PROCESO','FINALIZADA','CANCELADA','CERRADA_INCOMPLETA'), fecha_fin datetime(6), fecha_inicio datetime(6) not null, fecha_ultimo_cierre datetime(6), lote_producto_id bigint, lote_produccion varchar(255), version bigint, producto_id integer, responsable_id bigint, unidad_medida_id bigint, primary key (id)) ENGINE=InnoDB;
create table produccion (id bigint not null auto_increment, codigo_lote varchar(45) not null, estado enum ('CREADA','EN_PROCESO','FINALIZADA','CANCELADA','CERRADA_INCOMPLETA') not null, fecha_fin datetime(6), fecha_inicio datetime(6) not null, productos_id integer not null, usuarios_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table productos (id integer not null auto_increment, activo bit not null, codigo_sku varchar(50) not null, descripcion_producto varchar(255), fecha_creacion datetime(6) not null, nombre varchar(100) not null, rendimiento_unidad decimal(38,2), stock_minimo decimal(38,2) not null, stock_minimo_proveedor decimal(38,2), tipo_analisis_calidad enum ('NINGUNO','FISICO_QUIMICO','MICROBIOLOGICO','AMBOS') not null, categorias_producto_id bigint not null, usuarios_id bigint not null, unidades_medida_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table proveedores (id integer not null auto_increment, activo bit not null, direccion varchar(150), email varchar(100), nit_cedula varchar(20) not null, proveedor varchar(100) not null, nombre_contacto varchar(100) not null, pagina_web varchar(150), telefono_contacto varchar(20), primary key (id)) ENGINE=InnoDB;
create table recepciones_oc (id bigint not null auto_increment, codigo varchar(32) not null, created_at datetime(6) not null, fecha_recepcion date not null, observaciones varchar(500), almacen_destino_id integer not null, orden_compra_id integer not null, proveedor_id integer, usuario_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table recepciones_oc_detalles (id bigint not null auto_increment, cantidad_recibida decimal(18,6) not null, lotes_productos_id bigint, orden_compra_detalle_id bigint not null, productos_id integer not null, recepcion_oc_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table reservas_lote (id bigint not null auto_increment, cantidad_consumida decimal(18,6) not null, cantidad_reservada decimal(18,6) not null, created_at datetime(6) not null, estado enum ('ACTIVA','CONSUMIDA','CANCELADA') not null, updated_at datetime(6) not null, lote_id bigint not null, solicitud_movimiento_detalle_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table retencion_lote (id bigint not null auto_increment, causa TEXT not null, estado ENUM('RETENIDO','LIBERADO') not null, fecha_liberacion datetime(6), fecha_retencion datetime(6) not null, aprobado_por_id bigint not null, lote_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table secuencias_recepcion (id bigint not null auto_increment, actualizado_en datetime(6) not null, anio integer not null, prefijo varchar(16) not null, secuencia_actual bigint not null, primary key (id)) ENGINE=InnoDB;
create table solicitudes_movimiento (id bigint not null auto_increment, cantidad decimal(10,2) not null, codigo_lote varchar(255), estado enum ('PENDIENTE','AUTORIZADA','PARCIAL','RECHAZADO','EJECUTADA','RESERVADA','ATENDIDA','CANCELADA') not null, fecha_resolucion datetime(6), fecha_solicitud datetime(6) not null, fecha_vencimiento datetime(6), observaciones varchar(255), tipo_movimiento enum ('AJUSTE','DEVOLUCION','ENTRADA','RECEPCION','SALIDA','TRANSFERENCIA') not null, almacen_destino_id integer, almacen_origen_id integer, lote_id bigint, motivo_movimiento_id bigint, orden_compra_id integer, orden_produccion_id bigint, producto_id integer not null, proveedor_id integer, tipo_movimiento_detalle_id bigint, usuario_responsable_id bigint, usuario_solicitante_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table solicitudes_movimiento_detalle (id bigint not null auto_increment, cantidad decimal(18,6) not null, cantidad_atendida decimal(18,6), estado enum ('PENDIENTE','PARCIAL','ATENDIDO','CANCELADO') not null, almacen_destino_id integer, almacen_origen_id integer, lote_id bigint not null, solicitud_movimiento_id bigint not null, primary key (id)) ENGINE=InnoDB;
create table tipos_movimiento_detalle (id bigint not null auto_increment, descripcion varchar(100) not null, primary key (id)) ENGINE=InnoDB;
create table unidades_medida (id bigint not null auto_increment, nombre varchar(50) not null, simbolo varchar(5) not null, primary key (id)) ENGINE=InnoDB;
create table usuarios (id bigint not null auto_increment, activo bit not null, bloqueado bit not null, clave varchar(80) not null, codigo_2fa varchar(6), codigo_2fa_expira_en datetime(6), correo varchar(45) not null, nombre_completo varchar(100) not null, nombre_usuario varchar(45) not null, rol enum ('ROL_MICROBIOLOGO','ROL_JEFE_CALIDAD','ROL_ANALISTA_CALIDAD','ROL_JEFE_ALMACENES','ROL_ALMACENISTA','ROL_JEFE_PRODUCCION','ROL_LIDER_HOMEOPATICOS','ROL_LIDER_ALIMENTOS','ROL_CONTADOR','ROL_COMPRADOR','ROL_SUPER_ADMIN') not null, primary key (id)) ENGINE=InnoDB;
create table vida_util_productos (producto_id integer not null, semanas_vigencia integer not null, primary key (producto_id)) ENGINE=InnoDB;
alter table almacenes add constraint UK_4ilm0f1weyncwuyyikn7rrlf4 unique (nombre);
alter table categorias_producto add constraint un_nombre_categoria_UNIQUE unique (nombre);
create index idx_cierres_produccion_fecha on cierres_produccion (fecha_cierre);
alter table etapa_produccion add constraint UKs4ccujd45rmn6cptfuyti6okk unique (orden_produccion_id, nombre_etapa);
alter table evaluaciones_calidad add constraint uk_lote_tipo_evaluacion unique (lotes_productos_id, tipo_evaluacion);
alter table lotes_productos add constraint uk_codigo_lote_producto_almacen unique (codigo_lote, productos_id, almacenes_id);
alter table motivos_movimiento add constraint UK_au7f2rrw76n2t6gf66hbg3ppk unique (descripcion);
alter table motivos_movimiento add constraint UK_l59oqld82c969g5ls1n1lw7b5 unique (motivo);
alter table movimientos_inventario add constraint UK_qtkpre58rf4syhxrea246tb0x unique (solicitud_movimiento_id);
alter table no_conformidad add constraint UKd433rdpvdtomvuhpt2elg6g40 unique (codigo);
alter table ordenes_compra add constraint UK_j1oqhsagw5q9usri3on9yxbv3 unique (codigo_orden);
alter table orden_produccion add constraint UK_5eg82tlxfkvwwjeiwpwjomr76 unique (codigo_orden);
alter table productos add constraint un_sku_UNIQUE unique (codigo_sku);
alter table productos add constraint un_nombre_producto_UNIQUE unique (nombre);
alter table proveedores add constraint UK_b3k7hy6nk59ivbito83avgfyi unique (email);
alter table proveedores add constraint UK_aam5ceskyvm55pjvw3qduv99v unique (nit_cedula);
alter table proveedores add constraint UK_5pbt5osgelys10plmc0fjwx9i unique (proveedor);
alter table recepciones_oc add constraint uk_recepciones_oc_codigo unique (codigo);
alter table recepciones_oc add constraint uk_recepciones_oc_orden_fecha unique (orden_compra_id, fecha_recepcion);
create index idx_reservas_lote_lote_id on reservas_lote (lote_id);
create index idx_reservas_lote_detalle_id on reservas_lote (solicitud_movimiento_detalle_id);
create index idx_reservas_lote_lote_estado on reservas_lote (lote_id, estado);
alter table secuencias_recepcion add constraint uk_secuencias_recepcion_anio_prefijo unique (anio, prefijo);
alter table tipos_movimiento_detalle add constraint UKs249ev235o3nvyubknibvx77v unique (descripcion);
alter table unidades_medida add constraint un_nombre_UNIQUE unique (nombre);
alter table unidades_medida add constraint un_simbolo_UNIQUE unique (simbolo);
alter table usuarios add constraint un_nombre_usuario_UNIQUE unique (nombre_usuario);
alter table ajustes_inventario add constraint fk_ajuste_almacen foreign key (almacenes_id) references almacenes (id);
alter table ajustes_inventario add constraint fk_ajuste_producto foreign key (productos_id) references productos (id);
alter table ajustes_inventario add constraint fk_ajuste_usuario foreign key (usuarios_id) references usuarios (id);
alter table archivos_evaluacion add constraint FKomn7k9m0mt9jg7ycdbyij4dit foreign key (evaluacion_id) references evaluaciones_calidad (id);
alter table bitacora_cambios_inventario add constraint fk_bitacora_usuario foreign key (usuarios_id) references usuarios (id);
alter table capa add constraint fk_capa_no_conformidad foreign key (no_conformidad_id) references no_conformidad (id);
alter table capa add constraint fk_capa_responsable foreign key (responsable_id) references usuarios (id);
alter table checklist_calidad add constraint fk_checklist_creado_por foreign key (creado_por_id) references usuarios (id);
alter table cierres_produccion add constraint FKpbcu8girvpseocbck5daccbff foreign key (orden_produccion_id) references orden_produccion (id);
alter table control_calidad_proceso add constraint FKdikyos1muegvp0jk5r3bvkda0 foreign key (detalle_etapa_id) references detalle_etapa (id);
alter table control_calidad_proceso add constraint FK7a5f3w9u7i08m0t300fcbn2y0 foreign key (evaluado_por_id) references usuarios (id);
alter table detalle_etapa add constraint FKkht6xc249dvx8ranoaohamgx0 foreign key (etapa_id) references etapa_produccion (id);
alter table detalle_etapa add constraint FK63ybhcf0375vjvxpjf3if00oj foreign key (usuario_id) references usuarios (id);
alter table detalle_etapa add constraint FKun95som9uvc896fe8xb3aq4h foreign key (orden_produccion_id) references orden_produccion (id);
alter table detalle_formula add constraint FK6v2qkrsdpfb268dk1pa0vwekf foreign key (formula_id) references formula_producto (id);
alter table detalle_formula add constraint FKf2wmd1dck7dqppv20snynk6kd foreign key (insumo_id) references productos (id);
alter table detalle_formula add constraint FK5buogyws5o6poaq7ghoye26xx foreign key (unidad_medida_id) references unidades_medida (id);
alter table documento_formula add constraint FKm9gx0tnwjuuff9y7ex4y3k55y foreign key (formula_id) references formula_producto (id);
alter table documento_formula add constraint FKsi5eiyxuyq6fjwt2xaxstdfgt foreign key (usuario_id) references usuarios (id);
alter table especificaciones_calidad add constraint fk_espec_calidad_producto foreign key (productos_id) references productos (id);
alter table etapa_produccion add constraint FKk8lmqajbjc5yrr30kl7uc3rq9 foreign key (orden_produccion_id) references orden_produccion (id);
alter table etapa_plantilla add constraint FKop6i0ocwsn4ytsdf46dawyk6s foreign key (producto_id) references productos (id);
alter table evaluaciones_calidad add constraint fk_eval_lote foreign key (lotes_productos_id) references lotes_productos (id);
alter table evaluaciones_calidad add constraint fk_eval_usuario foreign key (usuarios_id) references usuarios (id);
alter table formula_producto add constraint FKpvcyq119qs2gj18qnx2uxj2uj foreign key (actualizado_por_id) references usuarios (id);
alter table formula_producto add constraint FKhkl0qyrh1tfdg70xfc2xkdbil foreign key (creado_por_id) references usuarios (id);
alter table formula_producto add constraint FKha59up23rtfvxv3xai8t22tp foreign key (producto_id) references productos (id);
alter table historial_estado_orden add constraint FK2p55ys3u2ey5ghop6a2stnx75 foreign key (usuario_id) references usuarios (id);
alter table historial_estado_orden add constraint FKn5awpmmxb0y0eeybcfu3irla foreign key (orden_compra_id) references ordenes_compra (id);
alter table item_checklist add constraint fk_item_checklist foreign key (checklist_id) references checklist_calidad (id);
alter table item_checklist add constraint fk_item_revisado_por foreign key (revisado_por_id) references usuarios (id);
alter table lotes_productos add constraint fk_lotes_productos_almacen foreign key (almacenes_id) references almacenes (id);
alter table lotes_productos add constraint FKd2sqmw528rf7nn3v5jn99yivp foreign key (orden_produccion_id) references orden_produccion (id);
alter table lotes_productos add constraint FKixhlwf7mx3nfllg2ny0wwu7st foreign key (produccion_id) references produccion (id);
alter table lotes_productos add constraint fk_lotes_productos_producto foreign key (productos_id) references productos (id);
alter table lotes_productos add constraint fk_lotes_productos_usuario_liberador foreign key (usuarios_liberador_id) references usuarios (id);
alter table movimientos_inventario add constraint fk_movimientos_inventario_destino foreign key (almacen_destino_id) references almacenes (id);
alter table movimientos_inventario add constraint fk_movimientos_inventario_origen foreign key (almacen_origen_id) references almacenes (id);
alter table movimientos_inventario add constraint fk_movimientos_inventario_lotes_productos1 foreign key (lotes_productos_id) references lotes_productos (id);
alter table movimientos_inventario add constraint fk_movimientos_inventario_motivos_movimiento1 foreign key (motivos_movimiento_id) references motivos_movimiento (id);
alter table movimientos_inventario add constraint fk_movimientos_inventario_ordenes_compra1 foreign key (ordenes_compra_id) references ordenes_compra (id);
alter table movimientos_inventario add constraint fk_movimientos_inventario_orden_compra_detalle foreign key (orden_compra_detalle_id) references orden_compra_detalle (id);
alter table movimientos_inventario add constraint FKioj7mj2gus2mm1ci4bd5rnkho foreign key (orden_produccion_id) references orden_produccion (id);
alter table movimientos_inventario add constraint fk_movimientos_inventario_productos1 foreign key (productos_id) references productos (id);
alter table movimientos_inventario add constraint fk_movimientos_inventario_proveedores1 foreign key (proveedores_id) references proveedores (id);
alter table movimientos_inventario add constraint fk_movimientos_inventario_recepcion_oc foreign key (recepcion_oc_id) references recepciones_oc (id);
alter table movimientos_inventario add constraint fk_movimientos_inventario_registrado_por foreign key (registrado_por_id) references usuarios (id);
alter table movimientos_inventario add constraint FK2tnvjvcf8v9bl1x2crsrx4quu foreign key (solicitud_movimiento_id) references solicitudes_movimiento (id);
alter table movimientos_inventario add constraint fk_mov_inv_tipo_mov_detalle foreign key (tipos_movimiento_detalle_id) references tipos_movimiento_detalle (id);
alter table no_conformidad add constraint fk_no_conf_usuario_reporta foreign key (usuario_reporta_id) references usuarios (id);
alter table orden_compra_detalle add constraint FKjmr0d9ethci4qna4xqvnth9tn foreign key (ordenes_compra_id) references ordenes_compra (id);
alter table orden_compra_detalle add constraint FK1dx5ia6jctm2rg62tw4clfp5 foreign key (productos_id) references productos (id);
alter table ordenes_compra add constraint fk_orden_compra_proveedor foreign key (proveedor_id) references proveedores (id);
alter table orden_produccion add constraint FKjjk54wuxbbxo9vnc5cw3dkfbp foreign key (producto_id) references productos (id);
alter table orden_produccion add constraint FKc5omumialgsl3kj8feprutjmw foreign key (responsable_id) references usuarios (id);
alter table orden_produccion add constraint FK7vptnf5vryodmm1swubt3vy9b foreign key (unidad_medida_id) references unidades_medida (id);
alter table produccion add constraint FKhr4w63b1kbqdkldb7c34ojq1u foreign key (productos_id) references productos (id);
alter table produccion add constraint FK9o8afbjm61ux8k5kgu9yuuac3 foreign key (usuarios_id) references usuarios (id);
alter table productos add constraint fk_productos_categorias_producto1 foreign key (categorias_producto_id) references categorias_producto (id);
alter table productos add constraint fk_productos_usuarios1 foreign key (usuarios_id) references usuarios (id);
alter table productos add constraint fk_productos_unidades_medida foreign key (unidades_medida_id) references unidades_medida (id);
alter table recepciones_oc add constraint fk_recepciones_oc_almacen_destino foreign key (almacen_destino_id) references almacenes (id);
alter table recepciones_oc add constraint fk_recepciones_oc_orden_compra foreign key (orden_compra_id) references ordenes_compra (id);
alter table recepciones_oc add constraint fk_recepciones_oc_proveedor foreign key (proveedor_id) references proveedores (id);
alter table recepciones_oc add constraint fk_recepciones_oc_usuario foreign key (usuario_id) references usuarios (id);
alter table recepciones_oc_detalles add constraint fk_recepciones_oc_detalles_lote foreign key (lotes_productos_id) references lotes_productos (id);
alter table recepciones_oc_detalles add constraint fk_recepciones_oc_detalles_orden_compra_detalle foreign key (orden_compra_detalle_id) references orden_compra_detalle (id);
alter table recepciones_oc_detalles add constraint fk_recepciones_oc_detalles_producto foreign key (productos_id) references productos (id);
alter table recepciones_oc_detalles add constraint fk_recepciones_oc_detalles_recepcion foreign key (recepcion_oc_id) references recepciones_oc (id);
alter table reservas_lote add constraint fk_reservas_lote_lote foreign key (lote_id) references lotes_productos (id);
alter table reservas_lote add constraint fk_reservas_lote_detalle foreign key (solicitud_movimiento_detalle_id) references solicitudes_movimiento_detalle (id);
alter table retencion_lote add constraint fk_retencion_usuario foreign key (aprobado_por_id) references usuarios (id);
alter table retencion_lote add constraint fk_retencion_lote foreign key (lote_id) references lotes_productos (id);
alter table solicitudes_movimiento add constraint FK4b96h2ycapp2r2sjca56j4aiv foreign key (almacen_destino_id) references almacenes (id);
alter table solicitudes_movimiento add constraint FKmye09btrhvy7ffu9q03q2q2qc foreign key (almacen_origen_id) references almacenes (id);
alter table solicitudes_movimiento add constraint FKr8srrvaid4rlqefuxja95rgoc foreign key (lote_id) references lotes_productos (id);
alter table solicitudes_movimiento add constraint FK2w8rgyhr1kwrj8licchry3dws foreign key (motivo_movimiento_id) references motivos_movimiento (id);
alter table solicitudes_movimiento add constraint FKjcsull7qxxh4k97oqslq8y9cf foreign key (orden_compra_id) references ordenes_compra (id);
alter table solicitudes_movimiento add constraint FKjatg6n3v2wnxai4antwbs5ck5 foreign key (orden_produccion_id) references orden_produccion (id);
alter table solicitudes_movimiento add constraint FKia1hoh9ognuvpnuu5umsklan5 foreign key (producto_id) references productos (id);
alter table solicitudes_movimiento add constraint FKrsj16p1ru9lpw8fkjymays5ay foreign key (proveedor_id) references proveedores (id);
alter table solicitudes_movimiento add constraint FKj77hy0ras69ci2ytdufgv1chg foreign key (tipo_movimiento_detalle_id) references tipos_movimiento_detalle (id);
alter table solicitudes_movimiento add constraint FKbr3aooj13olkqx8sgd7e8n3qu foreign key (usuario_responsable_id) references usuarios (id);
alter table solicitudes_movimiento add constraint FKnrdgobvfnet3petk6uj5mgk3x foreign key (usuario_solicitante_id) references usuarios (id);
alter table solicitudes_movimiento_detalle add constraint FKkqgoeqh3nm924fg7g6u4vynu foreign key (almacen_destino_id) references almacenes (id);
alter table solicitudes_movimiento_detalle add constraint FKqgnmltqe611mlu52ads3sowyg foreign key (almacen_origen_id) references almacenes (id);
alter table solicitudes_movimiento_detalle add constraint FK7uc40hm243k3bc6q2dcl9uy6j foreign key (lote_id) references lotes_productos (id);
alter table solicitudes_movimiento_detalle add constraint FK48nflkfuginw4bkljw4gsfm6n foreign key (solicitud_movimiento_id) references solicitudes_movimiento (id);
alter table vida_util_productos add constraint fk_vida_util_productos_producto foreign key (producto_id) references productos (id);
