ALTER TABLE movimientos_inventario
    MODIFY clasificacion ENUM (
        'AJUSTE_NEGATIVO',
        'AJUSTE_POSITIVO',
        'DEVOLUCION_DESDE_PRODUCCION',
        'DEVOLUCION_DE_PROVEEDOR',
        'DEVOLUCION_A_PROVEEDOR',
        'ENTRADA_PRODUCTO_TERMINADO',
        'ENTRADA_REPROCESO',
        'RECEPCION_COMPRA',
        'RECEPCION_DEVOLUCION_CLIENTE',
        'SALIDA_MUESTRA_CALIDAD',
        'SALIDA_PRODUCCION',
        'SALIDA_CLIENTE',
        'TRANSFERENCIA_INTERNA_PRODUCCION',
        'TRANSFERENCIA_GENERAL',
        'LIBERACION_CALIDAD',
        'RECHAZO_CALIDAD',
        'REGULARIZACION_TRAZABILIDAD',
        'REGULARIZACION_TRAZABILIDAD_PT'
    ) NOT NULL;
