-- Agrega clasificación y motivo para corrección operativa de salida a cliente

ALTER TABLE motivos_movimiento
    MODIFY COLUMN motivo ENUM(
        'AJUSTE_NEGATIVO',
        'AJUSTE_POSITIVO',
        'DEVOLUCION_DESDE_PRODUCCION',
        'DEVOLUCION_DE_PROVEEDOR',
        'DEVOLUCION_A_PROVEEDOR',
        'ENTRADA_PRODUCTO_TERMINADO',
        'ENTRADA_REPROCESO',
        'RECEPCION_COMPRA',
        'RECEPCION_DEVOLUCION_CLIENTE',
        'SALIDA_MUESTRA_CALIDAD',
        'SALIDA_PRODUCCION',
        'SALIDA_CLIENTE',
        'CORRECCION_SALIDA_CLIENTE',
        'TRANSFERENCIA_INTERNA_PRODUCCION',
        'TRANSFERENCIA_GENERAL',
        'LIBERACION_CALIDAD',
        'RECHAZO_CALIDAD'
    ) NOT NULL;

ALTER TABLE movimientos_inventario
    MODIFY COLUMN clasificacion ENUM(
        'AJUSTE_NEGATIVO',
        'AJUSTE_POSITIVO',
        'DEVOLUCION_DESDE_PRODUCCION',
        'DEVOLUCION_DE_PROVEEDOR',
        'DEVOLUCION_A_PROVEEDOR',
        'ENTRADA_PRODUCTO_TERMINADO',
        'ENTRADA_REPROCESO',
        'RECEPCION_COMPRA',
        'RECEPCION_DEVOLUCION_CLIENTE',
        'SALIDA_MUESTRA_CALIDAD',
        'SALIDA_PRODUCCION',
        'SALIDA_CLIENTE',
        'CORRECCION_SALIDA_CLIENTE',
        'TRANSFERENCIA_INTERNA_PRODUCCION',
        'TRANSFERENCIA_GENERAL',
        'LIBERACION_CALIDAD',
        'RECHAZO_CALIDAD'
    );

INSERT INTO motivos_movimiento (motivo, descripcion)
SELECT 'CORRECCION_SALIDA_CLIENTE', 'Corrección operativa de salida a cliente'
WHERE NOT EXISTS (
    SELECT 1 FROM motivos_movimiento WHERE motivo = 'CORRECCION_SALIDA_CLIENTE'
);
