-- Agrega nuevo valor PRODUCTO_SEMI_ELABORADO al enum de categorias_producto.tipo
ALTER TABLE categorias_producto
    MODIFY COLUMN tipo ENUM('MATERIA_PRIMA','PRODUCTO_TERMINADO','MATERIAL_EMPAQUE','SUMINISTROS','REPUESTOS','OBSOLETOS','PRODUCTO_SEMI_ELABORADO') NOT NULL;

INSERT INTO categorias_producto (nombre, tipo)
SELECT 'PRODUCTO SEMIELABORADO', 'PRODUCTO_SEMI_ELABORADO'
WHERE NOT EXISTS (
    SELECT 1 FROM categorias_producto WHERE tipo = 'PRODUCTO_SEMI_ELABORADO'
);
