CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL,
    nombre VARCHAR(120),
    activo BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_roles_codigo ON roles (codigo);

CREATE TABLE IF NOT EXISTS permisos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(120) NOT NULL,
    modulo VARCHAR(40) NOT NULL,
    accion VARCHAR(40) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_permisos_codigo ON permisos (codigo);

CREATE TABLE IF NOT EXISTS roles_permisos (
    rol_id BIGINT NOT NULL,
    permiso_id BIGINT NOT NULL,
    CONSTRAINT fk_roles_permisos_rol FOREIGN KEY (rol_id) REFERENCES roles (id),
    CONSTRAINT fk_roles_permisos_permiso FOREIGN KEY (permiso_id) REFERENCES permisos (id),
    CONSTRAINT pk_roles_permisos PRIMARY KEY (rol_id, permiso_id)
);
