package com.willyes.clemenintegra.inventario.domain.enums;

public enum TipoMovimientoDetalle {
    RECEPCION_COMPRA,
    RECEPCION_DEVOLUCION_CLIENTE,

    AJUSTE_POSITIVO,
    AJUSTE_NEGATIVO,

    SALIDA_PRODUCCION,
    ENTRADA_PRODUCCION,

    TRANSFERENCIA_ENTRADA,
    TRANSFERENCIA_SALIDA,

    DEVOLUCION_PROVEEDOR,

    SALIDA_MUESTRA,
    SALIDA_OBSOLETO,
    SALIDA_DONACION,
    SALIDA_RETIRO_MERCADO,
    SALIDA_PERDIDA,
    SALIDA_VENCIDO,
    SALIDA_MANTENIMIENTO,

    ENTRADA_REPROCESO,
    SALIDA_REPROCESO,

    SALIDA_ASEGURAMIENTO_CALIDAD,
    ENTRADA_ASEGURAMIENTO_CALIDAD
}


