package com.willyes.clemenintegra.shared.exception;

import org.springframework.http.HttpStatus;

/**
 * Códigos estandarizados para responder errores funcionales de la API.
 */
public enum ApiErrorCode {

    BLOQUEO_RETENCION_NC(HttpStatus.CONFLICT),
    BLOQUEO_NC_ACTIVA(HttpStatus.CONFLICT),
    BLOQUEO_CONDICION_USO(HttpStatus.CONFLICT),
    BLOQUEO_ESTADO_CUARENTENA(HttpStatus.CONFLICT),
    CALIDAD_LOTE_NO_LIBERADO(HttpStatus.UNPROCESSABLE_ENTITY),
    CALIDAD_TIPO_ANALISIS_NO_PERMITIDO(HttpStatus.BAD_REQUEST),
    RETENCION_LOTE_REQUERIDO(HttpStatus.UNPROCESSABLE_ENTITY),
    RETENCION_LOTE_NO_ENCONTRADO(HttpStatus.UNPROCESSABLE_ENTITY),
    RETENCION_ESTADO_NO_PERMITIDO(HttpStatus.UNPROCESSABLE_ENTITY),
    RETENCION_MOTIVO_INVALIDO(HttpStatus.UNPROCESSABLE_ENTITY),
    RETENCION_FECHA_INVALIDA(HttpStatus.UNPROCESSABLE_ENTITY),
    RETENCION_CAUSA_REQUERIDA(HttpStatus.UNPROCESSABLE_ENTITY),
    RETENCION_APROBADOR_REQUERIDO(HttpStatus.UNPROCESSABLE_ENTITY),
    RETENCION_APROBADOR_NO_ENCONTRADO(HttpStatus.UNPROCESSABLE_ENTITY),
    RETENCION_NO_ENCONTRADA(HttpStatus.NOT_FOUND),
    RETENCION_NO_ACTIVA(HttpStatus.UNPROCESSABLE_ENTITY),
    RETENCION_NC_NO_CERRADA(HttpStatus.CONFLICT),
    NC_ABIERTA(HttpStatus.CONFLICT),
    NC_NO_ENCONTRADA(HttpStatus.NOT_FOUND),
    NC_YA_CERRADA(HttpStatus.CONFLICT),
    NC_CAPA_REQUERIDA(HttpStatus.CONFLICT),
    EVALUACIONES_FALTANTES(HttpStatus.UNPROCESSABLE_ENTITY),
    DOCUMENTO_NO_ENCONTRADO(HttpStatus.NOT_FOUND),
    ROL_INSUFICIENTE(HttpStatus.FORBIDDEN),
    SUPER_ADMIN_SOLO_LECTURA(HttpStatus.FORBIDDEN),
    SOLICITUD_INVALIDA(HttpStatus.BAD_REQUEST),
    SOLICITUD_DETALLE_INCOMPLETO(HttpStatus.UNPROCESSABLE_ENTITY),
    KARDEX_PARAM_INVALIDO(HttpStatus.UNPROCESSABLE_ENTITY),
    RECURSO_NO_ENCONTRADO(HttpStatus.NOT_FOUND),
    OPERACION_NO_PERMITIDA(HttpStatus.CONFLICT),
    ERROR_INTERNO(HttpStatus.INTERNAL_SERVER_ERROR),
    NEGOCIO_GENERICO(HttpStatus.BAD_REQUEST),
    LOTE_INVALIDO_CONTEO(HttpStatus.BAD_REQUEST),
    STOCK_INSUFICIENTE(HttpStatus.BAD_REQUEST),
    PREBODEGA_ORIGEN_INVALIDO(HttpStatus.UNPROCESSABLE_ENTITY),
    SOLICITUD_ORIGEN_DESTINO_IGUALES(HttpStatus.UNPROCESSABLE_ENTITY),
    VIDA_UTIL_SOLO_PRODUCTO_TERMINADO(HttpStatus.BAD_REQUEST),
    VIDA_UTIL_SEMANAS_INVALIDAS(HttpStatus.BAD_REQUEST),
    VIDA_UTIL_NO_CONFIGURADA(HttpStatus.UNPROCESSABLE_ENTITY),
    MOVIMIENTO_DUPLICADO(HttpStatus.CONFLICT),
    UBICACION_NO_ENCONTRADA(HttpStatus.UNPROCESSABLE_ENTITY),
    UBICACION_NO_PERTENECE_ALMACEN(HttpStatus.UNPROCESSABLE_ENTITY),
    OBSERVACION_REQUERIDA(HttpStatus.UNPROCESSABLE_ENTITY),
    CONTEO_ESTADO_INVALIDO(HttpStatus.CONFLICT),
    CONTEO_YA_APLICADO(HttpStatus.CONFLICT),
    CONTEO_DETALLE_INVALIDO(HttpStatus.UNPROCESSABLE_ENTITY),
    CONTEO_SIN_DETALLES(HttpStatus.BAD_REQUEST),
    CONTEO_APLICACION_DUPLICADA(HttpStatus.CONFLICT),
    LOTE_EN_ALMACEN_INVALIDO_PARA_RECHAZO(HttpStatus.UNPROCESSABLE_ENTITY),
    OC_TRANSICION_INVALIDA(HttpStatus.CONFLICT),
    CONSUMO_PREBODEGA_INSUFICIENTE(HttpStatus.UNPROCESSABLE_ENTITY),
    PICKLIST_LINEAS_REQUERIDAS(HttpStatus.BAD_REQUEST),
    PICKLIST_LINEA_INVALIDA(HttpStatus.BAD_REQUEST),
    PICKLIST_LOTE_INVALIDO(HttpStatus.UNPROCESSABLE_ENTITY),
    PICKLIST_STOCK_INSUFICIENTE(HttpStatus.UNPROCESSABLE_ENTITY),
    PICKLIST_ESTADO_INVALIDO(HttpStatus.CONFLICT),
    PICKLIST_DESACTUALIZADO(HttpStatus.CONFLICT),
    PICKLIST_PRODUCTO_NO_PT(HttpStatus.BAD_REQUEST),
    PICKLIST_VIDA_UTIL_INSUFICIENTE(HttpStatus.UNPROCESSABLE_ENTITY),
    OP_HOMEOPATICO_REQUIERE_CONFIRMACION(HttpStatus.CONFLICT),
    OP_HOMEOPATICO_MOTIVO_OBLIGATORIO(HttpStatus.UNPROCESSABLE_ENTITY),
    OP_SIN_ETAPA_ACTIVA(HttpStatus.UNPROCESSABLE_ENTITY),
    OP_MULTIPLES_ETAPAS_ACTIVAS(HttpStatus.UNPROCESSABLE_ENTITY),
    ETAPA_ACTIVA_AMBIGUA(HttpStatus.UNPROCESSABLE_ENTITY),
    ETAPA_YA_ACTIVA(HttpStatus.UNPROCESSABLE_ENTITY),
    ETAPA_NO_INICIADA(HttpStatus.UNPROCESSABLE_ENTITY),
    PRODUCCION_OTRA_ETAPA_ACTIVA(HttpStatus.CONFLICT),
    PRODUCCION_MULTIPLES_ETAPAS_ACTIVAS(HttpStatus.CONFLICT),
    CHECKLIST_ETAPA_INCOMPLETO(HttpStatus.UNPROCESSABLE_ENTITY),
    PRODUCCION_CHECKLIST_NO_CONFIGURADO(HttpStatus.UNPROCESSABLE_ENTITY),
    DEVOLUCION_PT_DATOS_INCOMPLETOS(HttpStatus.UNPROCESSABLE_ENTITY),
    DEVOLUCION_PT_LOTE_REQUERIDO(HttpStatus.UNPROCESSABLE_ENTITY),
    DEVOLUCION_PT_COMBINACION_INVALIDA(HttpStatus.UNPROCESSABLE_ENTITY),
    DEVOLUCION_PT_LEGACY_REQUIERE_OBSERVACIONES(HttpStatus.UNPROCESSABLE_ENTITY),
    CODIGO_LOTE_LEGACY_REQUERIDO(HttpStatus.UNPROCESSABLE_ENTITY),
    PRODUCTO_SIN_UNIDAD_MEDIDA(HttpStatus.UNPROCESSABLE_ENTITY),
    CATALOGO_FALTANTE(HttpStatus.INTERNAL_SERVER_ERROR),
    CATALOGO_TIPO_DETALLE_ENTRADA_FALTANTE(HttpStatus.INTERNAL_SERVER_ERROR),
    SESION_EXPIRADA(HttpStatus.UNAUTHORIZED),
    SESION_INACTIVA(HttpStatus.UNAUTHORIZED),
    SESION_INVALIDA(HttpStatus.UNAUTHORIZED);

    private final HttpStatus httpStatus;

    ApiErrorCode(HttpStatus httpStatus) {
        this.httpStatus = httpStatus;
    }

    public HttpStatus getHttpStatus() {
        return httpStatus;
    }

    public String getCode() {
        return name();
    }
}
