package com.willyes.clemenintegra.inventario.model.enums;

public enum ClasificacionMovimientoInventario {
    AJUSTE_NEGATIVO,
    AJUSTE_POSITIVO,

    DEVOLUCION_PRODUCCION_BODEGA,
    DEVOLUCION_PROVEEDOR,

    ENTRADA_ASEGURAMIENTO_CALIDAD,
    ENTRADA_PRODUCCION,
    ENTRADA_REPROCESO,

    INGRESO_PT_DESDE_PRODUCCION,

    RECEPCION_COMPRA,
    RECEPCION_DEVOLUCION_CLIENTE,

    SALIDA_AVERIADO,
    SALIDA_DONACION,
    SALIDA_MANTENIMIENTO,
    SALIDA_MUESTRA_CALIDAD,
    SALIDA_MUESTRA_GRATIS,
    SALIDA_OBSOLETO,
    SALIDA_PERDIDA,
    SALIDA_PRODUCCION,
    SALIDA_REPROCESO,
    SALIDA_RETIRO_MERCADO,
    SALIDA_VENCIDO,

    TRANSFERENCIA_BODEGA_PRODUCCION
}




