package com.willyes.clemenintegra.inventario.model.enums;

public enum ClasificacionMovimientoInventario {
    // AJUSTES
    AJUSTE_NEGATIVO,
    AJUSTE_POSITIVO,

    // DEVOLUCIONES
    DEVOLUCION_DESDE_PRODUCCION,
    DEVOLUCION_DE_PROVEEDOR,
    DEVOLUCION_A_PROVEEDOR,

    // ENTRADAS
    ENTRADA_PRODUCTO_TERMINADO,
    ENTRADA_REPROCESO,

    // RECEPCIONES
    RECEPCION_COMPRA,
    RECEPCION_DEVOLUCION_CLIENTE,

    // SALIDAS
    SALIDA_MUESTRA_CALIDAD, //
    SALIDA_PRODUCCION, //

    // TRANSFERENCIAS
    TRANSFERENCIA_INTERNA_PRODUCCION,
    TRANSFERENCIA_GENERAL,
    LIBERACION_CALIDAD
}




