package com.willyes.clemenintegra.inventario.model.enums;

public enum TipoMovimiento {
    RECEPCION_COMPRA,
    ENTRADA_PRODUCCION,
    ENTRADA_ASEGURAMIENTO_CALIDAD,
    ENTRADA_REPROCESO,

    SALIDA_PRODUCCION,
    SALIDA_VENTA,
    SALIDA_DONACION,
    SALIDA_OBSOLETO,
    SALIDA_RETIRO_MERCADO,
    SALIDA_PERDIDA,
    SALIDA_VENCIDO,
    SALIDA_MUESTRA,
    SALIDA_MANTENIMIENTO,
    SALIDA_ASEGURAMIENTO_CALIDAD,
    SALIDA_REPROCESO,

    AJUSTE_POSITIVO,
    AJUSTE_NEGATIVO,

    TRANSFERENCIA_ENTRADA,
    TRANSFERENCIA_SALIDA,

    RECEPCION_DEVOLUCION_CLIENTE,
    DEVOLUCION_PROVEEDOR
}


