CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(45) NOT NULL,
    clave VARCHAR(80) NOT NULL,
    nombre_completo VARCHAR(100) NOT NULL,
    correo VARCHAR(45) NOT NULL,
    rol VARCHAR(50) NOT NULL,
    activo BOOLEAN NOT NULL,
    bloqueado BOOLEAN NOT NULL,
    codigo_2fa VARCHAR(6),
    codigo_2fa_expira_en TIMESTAMP,
    session_version BIGINT NOT NULL DEFAULT 0,
    ultima_actividad TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS un_nombre_usuario_UNIQUE ON usuarios (nombre_usuario);

CREATE TABLE IF NOT EXISTS categorias_producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    tipo VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS unidades_medida (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    nombre_plural VARCHAR(60),
    simbolo VARCHAR(5) NOT NULL,
    codigo VARCHAR(4),
    simbolo_impresion VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_sku VARCHAR(50) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion_producto VARCHAR(255),
    stock_minimo DECIMAL(19,6) NOT NULL,
    stock_minimo_proveedor DECIMAL(19,6),
    lead_time_compra_dias INT,
    lead_time_produccion_dias INT,
    stock_seguridad DECIMAL(19,6),
    stock_maximo_planeacion DECIMAL(19,6),
    rendimiento_unidad DECIMAL(38,2),
    activo BOOLEAN NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    tipo_analisis_calidad VARCHAR(30) NOT NULL,
    requiere_analisis_fisico BOOLEAN NOT NULL,
    requiere_analisis_quimico BOOLEAN NOT NULL,
    requiere_analisis_microbiologico BOOLEAN NOT NULL,
    unidades_medida_id BIGINT NOT NULL,
    categorias_producto_id BIGINT NOT NULL,
    usuarios_id BIGINT NOT NULL,
    modo_control_inventario VARCHAR(30) NOT NULL,
    CONSTRAINT fk_productos_unidades_medida FOREIGN KEY (unidades_medida_id) REFERENCES unidades_medida (id),
    CONSTRAINT fk_productos_categorias_producto1 FOREIGN KEY (categorias_producto_id) REFERENCES categorias_producto (id),
    CONSTRAINT fk_productos_usuarios1 FOREIGN KEY (usuarios_id) REFERENCES usuarios (id)
);

CREATE TABLE IF NOT EXISTS plan_produccion_semanal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semana_inicio DATE NOT NULL,
    semana_fin DATE NOT NULL,
    estado VARCHAR(30) NOT NULL,
    comentarios VARCHAR(500),
    creado_por_id BIGINT,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_plan_semana_usuario FOREIGN KEY (creado_por_id) REFERENCES usuarios (id)
);

CREATE TABLE IF NOT EXISTS plan_produccion_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cantidad_planificada DECIMAL(19,6) NOT NULL,
    unidad_medida_id BIGINT,
    prioridad INT,
    origen_demanda VARCHAR(100),
    observacion VARCHAR(500),
    creado_por_id BIGINT,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_plan_det_plan FOREIGN KEY (plan_id) REFERENCES plan_produccion_semanal (id),
    CONSTRAINT fk_plan_det_producto FOREIGN KEY (producto_id) REFERENCES productos (id),
    CONSTRAINT fk_plan_det_unidad FOREIGN KEY (unidad_medida_id) REFERENCES unidades_medida (id),
    CONSTRAINT fk_plan_det_creado_por FOREIGN KEY (creado_por_id) REFERENCES usuarios (id)
);
