CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(45) NOT NULL,
    clave VARCHAR(80) NOT NULL,
    nombre_completo VARCHAR(100) NOT NULL,
    correo VARCHAR(45) NOT NULL,
    rol VARCHAR(50) NOT NULL,
    activo BOOLEAN NOT NULL,
    bloqueado BOOLEAN NOT NULL,
    codigo_2fa VARCHAR(6),
    codigo_2fa_expira_en TIMESTAMP,
    session_version BIGINT NOT NULL DEFAULT 0,
    ultima_actividad TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS un_nombre_usuario_UNIQUE ON usuarios (nombre_usuario);
