DROP TABLE IF EXISTS vida_util_productos;
DROP TABLE IF EXISTS productos;
DROP TABLE IF EXISTS plantillas_analisis_micro;
DROP TABLE IF EXISTS unidades_medida;
DROP TABLE IF EXISTS categorias_producto;
DROP TABLE IF EXISTS usuarios;

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(45) NOT NULL,
    clave VARCHAR(80) NOT NULL,
    nombre_completo VARCHAR(100) NOT NULL,
    correo VARCHAR(45) NOT NULL,
    rol VARCHAR(50) NOT NULL,
    activo BOOLEAN NOT NULL,
    bloqueado BOOLEAN NOT NULL,
    codigo_2fa VARCHAR(6),
    codigo_2fa_expira_en TIMESTAMP
);

CREATE TABLE categorias_producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    tipo VARCHAR(30) NOT NULL
);

CREATE TABLE unidades_medida (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    nombre_plural VARCHAR(60),
    simbolo VARCHAR(5) NOT NULL,
    codigo VARCHAR(4),
    simbolo_impresion VARCHAR(10)
);

CREATE TABLE plantillas_analisis_micro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL
);

CREATE TABLE productos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_sku VARCHAR(50) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion_producto VARCHAR(255),
    stock_minimo DECIMAL(19,2) NOT NULL,
    stock_minimo_proveedor DECIMAL(19,2),
    lead_time_compra_dias INTEGER,
    lead_time_produccion_dias INTEGER,
    stock_seguridad DECIMAL(19,6),
    stock_maximo_planeacion DECIMAL(19,6),
    rendimiento_unidad DECIMAL(38,2),
    activo BOOLEAN NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    tipo_analisis_calidad VARCHAR(30) NOT NULL,
    unidades_medida_id BIGINT NOT NULL,
    categorias_producto_id BIGINT NOT NULL,
    usuarios_id BIGINT NOT NULL,
    modo_control_inventario VARCHAR(30) NOT NULL,
    plantilla_micro_id BIGINT,
    CONSTRAINT fk_productos_unidades_medida FOREIGN KEY (unidades_medida_id) REFERENCES unidades_medida (id),
    CONSTRAINT fk_productos_categorias_producto1 FOREIGN KEY (categorias_producto_id) REFERENCES categorias_producto (id),
    CONSTRAINT fk_productos_usuarios1 FOREIGN KEY (usuarios_id) REFERENCES usuarios (id),
    CONSTRAINT fk_productos_plantilla_micro FOREIGN KEY (plantilla_micro_id) REFERENCES plantillas_analisis_micro (id)
);

CREATE TABLE vida_util_productos (
    producto_id INTEGER PRIMARY KEY,
    semanas_vigencia INTEGER NOT NULL,
    actualizado_por_id BIGINT,
    fecha_actualizacion TIMESTAMP,
    CONSTRAINT fk_vida_util_productos_producto FOREIGN KEY (producto_id) REFERENCES productos (id),
    CONSTRAINT fk_vida_util_productos_usuario FOREIGN KEY (actualizado_por_id) REFERENCES usuarios (id)
);
