ALTER TABLE plantillas_analisis_micro
    ADD COLUMN IF NOT EXISTS version INT NOT NULL DEFAULT 1;

ALTER TABLE no_conformidad
    ADD COLUMN IF NOT EXISTS tipo_incidente ENUM('NO_CONFORMIDAD','DESVIACION') NOT NULL DEFAULT 'NO_CONFORMIDAD';
